// RetailOps Kiosk station configuration example.
//
// Copy this file to config.local.js and replace the placeholders with values
// generated by the RetailOps Backend provisioning command:
//
//   python manage.py provision_kiosk --store <STORE_ID> --station <N> --by <admin-email>
//
// Never commit config.local.js. It contains the per-station Kiosk API key.

window.__KIOSK_CONFIG__ = {
  BASE_URL: "http://127.0.0.1:8000",
  API_PATH: "/api/v1",

  KIOSK_API_KEY: "<KIOSK_API_KEY>",

  STORE_NAME: "RetailOps Kiosk",
  STORE_ADDRESS: "Local store",
  KIOSK_STATION_NUMBER: "1",

  BRAND_LOGO_URL: "",
  BRAND_LOGO_ALT: "RetailOps Kiosk",
  BRAND_SUBTITLE: "autopago",
  BRAND_SHOW_TEXT: true,
  KIOSK_THEME: {
    primary: "#0057A8",
    primaryLight: "#1A72C8",
    primaryDark: "#003D7A",
    primarySoft: "#EEF5FF",
    primarySoftStrong: "#D6E8FF",
    accent: "#00CFFF",
    background: "#F4F6FA",
    surface: "#FFFFFF",
    text: "#1A2033",
    muted: "#6B7280",
    success: "#1D9E75",
    warning: "#EF9F27",
    danger: "#E24B4A",
    border: "rgba(0, 87, 168, 0.15)",
    onPrimary: "#FFFFFF",
    onPrimaryMuted: "rgba(255,255,255,0.72)",
    onPrimarySoft: "rgba(255,255,255,0.86)",
  },

  USD_TO_BS_RATE: 50.00,
  EXCHANGE_RATE_API_URL: "",

  CURRENCY_SYMBOL: "Bs.",
  DECIMAL_PLACES: 2,
  LOW_STOCK_THRESHOLD: 5,
  ENABLED_PAYMENT_METHODS: ["cash", "mobile_payment", "bank_transfer"],

  LOCALE: "es-VE",
  IDLE_TIMEOUT_SECONDS: 120,
  PROCESSING_TIMEOUT_SECONDS: 60,
  APP_VERSION: "2.3.7",
};
