#!/usr/bin/env bash
set -Eeuo pipefail

repo="https://github.com/jp72924/retailops-kiosk"
ref="main"
install_dir="${XDG_DATA_HOME:-$HOME/.local/share}/retailops-kiosk"
bin_dir="$HOME/.local/bin"
backend_url="${RETAILOPS_KIOSK_BACKEND_URL:-}"
api_key="${RETAILOPS_KIOSK_API_KEY:-}"
store_name="${RETAILOPS_KIOSK_STORE_NAME:-RetailOps Kiosk}"
store_address="${RETAILOPS_KIOSK_STORE_ADDRESS:-Local store}"
station="${RETAILOPS_KIOSK_STATION:-1}"
port="${RETAILOPS_KIOSK_PORT:-8080}"
create_service=true
assume_yes=false

usage() {
  cat <<'EOF'
Usage: install.sh [options]

Install RetailOps Kiosk as a standalone static PWA and generate config.local.js.

Options:
  --backend-url <url>       RetailOps Backend base URL, e.g. http://127.0.0.1:8000.
  --api-key <key>           Kiosk station API key generated by provision_kiosk.
  --store-name <name>       Store display name. Default: RetailOps Kiosk.
  --store-address <text>    Store display address. Default: Local store.
  --station <number>        Kiosk station number. Default: 1.
  --port <port>             Local HTTP port for launcher/service. Default: 8080.
  --dir <path>              Install directory. Default: ~/.local/share/retailops-kiosk.
  --repo <url>              GitHub repository URL. Default: jp72924/retailops-kiosk.
  --ref <branch-or-tag>     Branch or tag to install. Default: main.
  --yes                     Non-interactive mode; keep placeholders for missing values.
  --no-service              Do not create/start a systemd user service.
  -h, --help                Show this help.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --backend-url) backend_url="${2:?Missing value for --backend-url}"; shift 2 ;;
    --api-key) api_key="${2:?Missing value for --api-key}"; shift 2 ;;
    --store-name) store_name="${2:?Missing value for --store-name}"; shift 2 ;;
    --store-address) store_address="${2:?Missing value for --store-address}"; shift 2 ;;
    --station) station="${2:?Missing value for --station}"; shift 2 ;;
    --port) port="${2:?Missing value for --port}"; shift 2 ;;
    --dir) install_dir="${2:?Missing value for --dir}"; shift 2 ;;
    --repo) repo="${2:?Missing value for --repo}"; shift 2 ;;
    --ref) ref="${2:?Missing value for --ref}"; shift 2 ;;
    --yes) assume_yes=true; shift ;;
    --no-service) create_service=false; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage >&2; exit 2 ;;
  esac
done

need() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "Required command not found: $1" >&2
    exit 1
  fi
}

prompt_if_missing() {
  local name="$1"
  local current="$2"
  local prompt="$3"
  local default_value="${4:-}"

  if [[ -n "$current" ]]; then
    printf '%s' "$current"
    return
  fi

  if [[ "$assume_yes" == true ]]; then
    printf '%s' "$default_value"
    return
  fi

  if [[ ! -r /dev/tty ]]; then
    echo "Missing $name and no interactive terminal is available. Pass --$name or use --yes." >&2
    exit 1
  fi

  local value
  read -r -p "$prompt" value </dev/tty
  printf '%s' "${value:-$default_value}"
}

js_escape() {
  local value="$1"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  value="${value//$'\n'/ }"
  printf '%s' "$value"
}

need curl
need tar
need python3

backend_url="$(prompt_if_missing backend-url "$backend_url" "RetailOps Backend URL [http://127.0.0.1:8000]: " "http://127.0.0.1:8000")"
api_key="$(prompt_if_missing api-key "$api_key" "Kiosk API key [<KIOSK_API_KEY>]: " "<KIOSK_API_KEY>")"

tmp_dir="$(mktemp -d)"
cleanup() { rm -rf "$tmp_dir"; }
trap cleanup EXIT

archive_url="${repo%/}/archive/${ref}.tar.gz"
mkdir -p "$install_dir" "$bin_dir"

echo "Downloading RetailOps Kiosk from $archive_url"
curl -fsSL "$archive_url" | tar -xz --strip-components=1 -C "$tmp_dir"

rsync_available=false
if command -v rsync >/dev/null 2>&1; then
  rsync_available=true
fi

if [[ "$rsync_available" == true ]]; then
  rsync -a --delete --exclude '.git' --exclude 'config.local.js' "$tmp_dir/" "$install_dir/"
else
  find "$install_dir" -mindepth 1 ! -name 'config.local.js' -exec rm -rf {} +
  cp -R "$tmp_dir"/. "$install_dir"/
fi

cat > "$install_dir/config.local.js" <<EOF
// Generated by the RetailOps Kiosk installer.
// Do not commit this file.
window.__KIOSK_CONFIG__ = {
  BASE_URL: "$(js_escape "$backend_url")",
  API_PATH: "/api/v1",
  KIOSK_API_KEY: "$(js_escape "$api_key")",
  STORE_NAME: "$(js_escape "$store_name")",
  STORE_ADDRESS: "$(js_escape "$store_address")",
  KIOSK_STATION_NUMBER: "$(js_escape "$station")",
  ENABLED_PAYMENT_METHODS: ["cash", "mobile_payment", "bank_transfer"],
  APP_VERSION: "2.1.0",
};
EOF

cat > "$bin_dir/retailops-kiosk" <<EOF
#!/usr/bin/env bash
set -Eeuo pipefail
host="127.0.0.1"
port="${port}"
while [[ \$# -gt 0 ]]; do
  case "\$1" in
    --host) host="\${2:?Missing value for --host}"; shift 2 ;;
    --port) port="\${2:?Missing value for --port}"; shift 2 ;;
    -h|--help)
      echo "Usage: retailops-kiosk [--host 127.0.0.1] [--port 8080]"
      exit 0
      ;;
    *) echo "Unknown option: \$1" >&2; exit 2 ;;
  esac
done
echo "Serving RetailOps Kiosk at http://\$host:\$port/"
exec python3 -m http.server "\$port" --bind "\$host" --directory "$(js_escape "$install_dir")"
EOF
chmod +x "$bin_dir/retailops-kiosk"

if [[ "$create_service" == true ]] && command -v systemctl >/dev/null 2>&1 && systemctl --user status >/dev/null 2>&1; then
  service_dir="$HOME/.config/systemd/user"
  mkdir -p "$service_dir"
  cat > "$service_dir/retailops-kiosk.service" <<EOF
[Unit]
Description=RetailOps Kiosk local static server

[Service]
ExecStart=$bin_dir/retailops-kiosk --port $port
Restart=on-failure

[Install]
WantedBy=default.target
EOF
  systemctl --user daemon-reload
  systemctl --user enable --now retailops-kiosk.service
  echo "Started systemd user service: retailops-kiosk.service"
fi

echo
echo "RetailOps Kiosk installed in: $install_dir"
echo "Config written to: $install_dir/config.local.js"
echo "Launcher: $bin_dir/retailops-kiosk"
echo "Open: http://127.0.0.1:$port/"
if [[ "$api_key" == "<KIOSK_API_KEY>" ]]; then
  echo
  echo "Next step: replace <KIOSK_API_KEY> in config.local.js with a station key from RetailOps Backend."
fi
