<#
.SYNOPSIS
Install RetailOps Kiosk on Windows and generate config.local.js.
#>
[CmdletBinding()]
param(
    [string]$BackendUrl = $env:RETAILOPS_KIOSK_BACKEND_URL,
    [string]$ApiKey = $env:RETAILOPS_KIOSK_API_KEY,
    [string]$StoreName = $(if ($env:RETAILOPS_KIOSK_STORE_NAME) { $env:RETAILOPS_KIOSK_STORE_NAME } else { "RetailOps Kiosk" }),
    [string]$StoreAddress = $(if ($env:RETAILOPS_KIOSK_STORE_ADDRESS) { $env:RETAILOPS_KIOSK_STORE_ADDRESS } else { "Local store" }),
    [string]$Station = $(if ($env:RETAILOPS_KIOSK_STATION) { $env:RETAILOPS_KIOSK_STATION } else { "1" }),
    [int]$Port = $(if ($env:RETAILOPS_KIOSK_PORT) { [int]$env:RETAILOPS_KIOSK_PORT } else { 8080 }),
    [string]$Dir = $(Join-Path $env:LOCALAPPDATA "RetailOps\kiosk"),
    [string]$Repo = "https://github.com/jp72924/retailops-kiosk",
    [string]$Ref = "main",
    [switch]$Yes,
    [switch]$NoService
)

$ErrorActionPreference = "Stop"

function Read-Value {
    param(
        [string]$Name,
        [string]$Value,
        [string]$Prompt,
        [string]$Default
    )
    if ($Value) { return $Value }
    if ($Yes) { return $Default }
    $inputValue = Read-Host "$Prompt [$Default]"
    if ($inputValue) { return $inputValue }
    return $Default
}

function ConvertTo-JsString {
    param([string]$Value)
    return ($Value | ConvertTo-Json -Compress)
}

function Get-PythonCommand {
    $py = Get-Command py -ErrorAction SilentlyContinue
    if ($py) { return "py -3" }
    $python = Get-Command python -ErrorAction SilentlyContinue
    if ($python) { return "python" }
    throw "Python was not found. Install Python 3 and try again."
}

$BackendUrl = Read-Value -Name "backend-url" -Value $BackendUrl -Prompt "RetailOps Backend URL" -Default "http://127.0.0.1:8000"
$ApiKey = Read-Value -Name "api-key" -Value $ApiKey -Prompt "Kiosk API key" -Default "<KIOSK_API_KEY>"

$tmp = Join-Path ([System.IO.Path]::GetTempPath()) ("retailops-kiosk-" + [guid]::NewGuid().ToString("N"))
$zip = Join-Path $tmp "retailops-kiosk.zip"
$extract = Join-Path $tmp "extract"
New-Item -ItemType Directory -Force -Path $tmp, $extract | Out-Null

try {
    $archiveUrl = ($Repo.TrimEnd("/") + "/archive/" + $Ref + ".zip")
    Write-Host "Downloading RetailOps Kiosk from $archiveUrl"
    Invoke-WebRequest -Uri $archiveUrl -OutFile $zip
    Expand-Archive -Path $zip -DestinationPath $extract -Force

    $source = Get-ChildItem -Path $extract -Directory | Select-Object -First 1
    if (-not $source) { throw "Downloaded archive did not contain a project directory." }

    New-Item -ItemType Directory -Force -Path $Dir | Out-Null
    Get-ChildItem -Path $Dir -Force |
        Where-Object { $_.Name -ne "config.local.js" } |
        Remove-Item -Recurse -Force
    Copy-Item -Path (Join-Path $source.FullName "*") -Destination $Dir -Recurse -Force

    $config = @"
// Generated by the RetailOps Kiosk installer.
// Do not commit this file.
window.__KIOSK_CONFIG__ = {
  BASE_URL: $(ConvertTo-JsString $BackendUrl),
  API_PATH: "/api/v1",
  KIOSK_API_KEY: $(ConvertTo-JsString $ApiKey),
  STORE_NAME: $(ConvertTo-JsString $StoreName),
  STORE_ADDRESS: $(ConvertTo-JsString $StoreAddress),
  KIOSK_STATION_NUMBER: $(ConvertTo-JsString $Station),
  ENABLED_PAYMENT_METHODS: ["cash", "mobile_payment", "bank_transfer"],
  APP_VERSION: "2.1.0",
};
"@
    Set-Content -Path (Join-Path $Dir "config.local.js") -Value $config -Encoding UTF8

    $binDir = Join-Path $env:LOCALAPPDATA "RetailOps\bin"
    New-Item -ItemType Directory -Force -Path $binDir | Out-Null
    $launcher = Join-Path $binDir "retailops-kiosk.cmd"
    $pythonCommand = Get-PythonCommand
    $launcherContent = @"
@echo off
setlocal
set PORT=%~1
if "%PORT%"=="" set PORT=$Port
echo Serving RetailOps Kiosk at http://127.0.0.1:%PORT%/
$pythonCommand -m http.server %PORT% --bind 127.0.0.1 --directory "$Dir"
"@
    Set-Content -Path $launcher -Value $launcherContent -Encoding ASCII

    Write-Host ""
    Write-Host "RetailOps Kiosk installed in: $Dir"
    Write-Host "Config written to: $(Join-Path $Dir "config.local.js")"
    Write-Host "Launcher: $launcher"
    Write-Host "Open: http://127.0.0.1:$Port/"
    if ($ApiKey -eq "<KIOSK_API_KEY>") {
        Write-Host ""
        Write-Host "Next step: replace <KIOSK_API_KEY> in config.local.js with a station key from RetailOps Backend."
    }
}
finally {
    Remove-Item -Path $tmp -Recurse -Force -ErrorAction SilentlyContinue
}
